### PR TITLE
fix #92

### LINKED ISSUE #92: Return nonzero value on failure and print errors on stderr
When the docs generating fails the process should end up with a nonzero value to signal a failure (and to be able to leverage all the bash && or || syntax).
Also, the error message should be print on stderr, not stdout.

### PR DESCRIPTION
**Pull request by raphaelsoul**
hi i've fixed #92 that error not be captured and process always exit with zero return code

### CODE REVIEW

**Comment by raphaelsoul** [comment]
notice pls: need a build

File: src/swagger-inline.js [hunk 1]
```diff
@@ -94,18 +94,22 @@ function swaggerInline(globPatterns, providedOptions) {
...
+        })).then(() => {
+          log(`${endpoints.length} definitions found...`);
+          log(`${schemas.length} schemas found...`);
+
+          const baseObjWithEndpoints = mergeEndpointsWithBase(baseObj, endpoints);
+          const swagger = mergeSchemasWithBase(baseObjWithEndpoints, schemas);
+
+          return outputResult(swagger, options);
+        }).catch(e => {
+          console.error(e);
```
Comment (erunion) [inline src/swagger-inline.js:110]: Thoughts on throwing the error instead of putting it in the console?

**Comment by erunion** [comment]
Not sure why tests aren't building against this, but running them locally it's all good.

File: src/swagger-inline.js (hunk 1 above)
Comment (raphaelsoul) [reply src/swagger-inline.js:110]: yep throw the error will prevent writing error stack into target file and exit process with non-zero exit code
In previous version. u will get code zero but the generated file contains error message

Comment (raphaelsoul) [reply src/swagger-inline.js]: yep updated.
throwing it will be better than exit process directly.

Toolchains not triggers because I edited it on github web page lol. Thought it will be a small fix but found it wrong😆.

Btw wrote a test case to cover process exit code.

**Comment by erunion** [comment]
Published into v3.1.1. Thanks again for the help!
